In [1]:
import numpy as np

In [ ]:
arr1  = np.array([1,2,3,4,5,6,7,8,9])
print(arr1)
print(arr1.shape)
print(arr1.size)
print(arr1.ndim)
print(type(arr1))
print(arr1.dtype.name)
print(arr1.itemsize)

In [ ]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)
print(arr2.dtype.name)
arr1 = arr1.reshape(3,3)
print(arr1)

In [ ]:
arr4 = np.array([(1,2,3),(4,5,6)], dtype=complex)
print(arr4)

In [ ]:
np.zeros((3,4))
print(np.zeros((3,4)))
print(np.ones((3,3,3)))
print(np.empty((2,2)))

In [ ]:
arr5 = np.arange(1, 10, 2)
print(arr5)
np.arange(1,20, 0.5)
print(np.arange(1,20, 0.5))

In [ ]:
from numpy import pi
np.linspace(1, 10, 5,dtype=int)
print(np.linspace(1, 10, 5, dtype=int))
x = np.linspace(0, 2 * pi, 100)
f = np.sin(x)
print(f)

In [ ]:
a = np.arange(12)
print(a)
b = np.arange(36).reshape(2,3,6)
print(b)

In [ ]:
mx = np.array([1,2])
print(mx)

In [ ]:
arr3d = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr3d)
print(arr3d.shape)

In [ ]:
print(arr3d[0][1][2])

In [ ]:
print(arr3d[0,0,1])

In [ ]:
ar = np.array([1,2,3,4,5,6,7,8,9])
print(ar)
arr = ar.reshape(3,3)
print(arr)

In [ ]:
print(arr[1][1])

In [ ]:
arr[2][1] = 10
arr[1][1] = 10

print(arr)

In [ ]:
a1 = np.arange(35)
print(a1)
a2 = a1.reshape(1,5,7)
print(a2)

In [ ]:
a3 = a2.flatten()
print(a3)

In [ ]:
print(a3.ndim)

In [ ]:
a5 = np.arange(35).reshape(1,5,7)
print(a5.ndim)
print(a5)

In [ ]:
print(a5[0][0][0])

In [ ]:
print(a5[0:1:1])

In [ ]:
a7 = np.array([1,2,3,4,5,6,7,8,9])
a8 = a7.reshape(3,3)
print(a8)

In [ ]:
print(a8[1][1])

In [ ]:
a8[1][2]=5
print(a8)

In [ ]:
a9 = np.arange(35).reshape(5,7)
print(a9)
print("\nAccessing the 3D array elements......")
print(a9[1::5])

In [ ]:
print(a9.flatten())

In [ ]:
asd = np.arange(10000)
print(asd)

In [ ]:
asd.reshape(100, 100)
print(asd)

In [ ]:
b = np.array([1,2,3,4])
a = np.arange(4)
c = a+b
print(c)

In [9]:
ar1 = np.arange(8).reshape(2,4)
print("2 by 4 array.....")
print(ar1)
ar2 = np.arange(8).reshape(2,4)
print("\n3 by 3 array...... ")
print(ar2)
print("\nBroadcasting array1 and array2.....")
print(ar1*ar2)

2 by 4 array.....
[[0 1 2 3]
 [4 5 6 7]]

3 by 3 array...... 
[[0 1 2 3]
 [4 5 6 7]]

Broadcasting array1 and array2.....
[[ 0  1  4  9]
 [16 25 36 49]]


In [10]:
print(ar1 + ar2)

[[ 0  2  4  6]
 [ 8 10 12 14]]


In [5]:
are = np.arange(12).reshape(4,3)
print(are)
are1 = np.arange(12).reshape(4,3)
print(are1)
print(are * are1)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[  0   1   4]
 [  9  16  25]
 [ 36  49  64]
 [ 81 100 121]]
