In [1]:
# Objective: Demonstrate broadcasting and universal functions

import numpy as np

# 1. Create arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([10, 20, 30])

In [2]:
# 2. Broadcasting Operations
addition = arr1 + arr2
subtraction = arr1 - arr2
multiplication = arr1 * arr2
division = arr1 / arr2

print("Addition:\n", addition)
print("Subtraction:\n", subtraction)
print("Multiplication:\n", multiplication)
print("Division:\n", division)

Addition:
 [[11 22 33]
 [14 25 36]]
Subtraction:
 [[ -9 -18 -27]
 [ -6 -15 -24]]
Multiplication:
 [[ 10  40  90]
 [ 40 100 180]]
Division:
 [[0.1  0.1  0.1 ]
 [0.4  0.25 0.2 ]]


In [3]:
# Broadcasting Explanation:
# Broadcasting allows NumPy to perform operations on arrays of different shapes.
# arr2 is automatically expanded to match the shape of arr1 (2x3),
# so operations can be performed element-wise.

In [4]:
# 3. Universal Functions
arr3 = np.array([1, 4, 9, 16, 25])

print("\nSquare Root:", np.sqrt(arr3))
print("Exponential:", np.exp(arr3))
print("Sine:", np.sin(arr3))


Square Root: [1. 2. 3. 4. 5.]
Exponential: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]
Sine: [ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]


In [5]:
# 4. Array operations on arr4
arr4 = np.array([[5, 12, 3], [8, 2, 7]])

print("\nSum of all elements:", np.sum(arr4))
print("Max in each column:", np.max(arr4, axis=0))
print("Min in each row:", np.min(arr4, axis=1))


Sum of all elements: 37
Max in each column: [ 8 12  7]
Min in each row: [3 2]


In [6]:
# 5. Type casting arr1 to float
arr1_float = arr1.astype(float)
print("\narr1 converted to float:\n", arr1_float)


arr1 converted to float:
 [[1. 2. 3.]
 [4. 5. 6.]]
