In [10]:
import numpy as np

In [11]:
# array A
A = np.array([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])

#array B
B = np.zeros((3, 3))

# array C
C = np.random.randint(0, 5, 10)

# array D
D = np.linspace(0, 5, 10)

In [12]:
print("Array A:", A)
print("Array B:\n", B)
print("Array C:", C)
print("Array D:", D)

Array A: [ 2  4  6  8 10 12 14 16 18 20]
Array B:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array C: [2 3 1 3 4 1 2 4 2 0]
Array D: [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [13]:
print("Array A:", A)
print("Array B:\n", B)
print("Array C:", C)
print("Array D:", D)

Array A: [ 2  4  6  8 10 12 14 16 18 20]
Array B:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array C: [2 3 1 3 4 1 2 4 2 0]
Array D: [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [14]:
# Reshape
A_reshaped = A.reshape(2,5)
print("Reshaped A:\n", A_reshaped)

# Max and Min
print("Max value:", A.max())
print("Index of max value:", A.argmax())

print("Min value:", A.min())
print("Index of min value:", A.argmin())

Reshaped A:
 [[ 2  4  6  8 10]
 [12 14 16 18 20]]
Max value: 20
Index of max value: 9
Min value: 2
Index of min value: 0


In [15]:
E = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print("Element at row 1 column 2:", E[1,2])

Element at row 1 column 2: 6
